// This file was auto-generated by ML.NET Model Builder. 

using System;
using Covid_Vaccine_DistributionML.Model;

namespace Covid_Vaccine_DistributionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Stname = @"delhi",
                Stcase = 200F,
                Tovac = 500F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Stvac with predicted Stvac from sample data...\n\n");
            Console.WriteLine($"Stname: {sampleData.Stname}");
            Console.WriteLine($"Stcase: {sampleData.Stcase}");
            Console.WriteLine($"Tovac: {sampleData.Tovac}");
            Console.WriteLine($"\n\nPredicted Stvac: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
