// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Covid_Vaccine_DistributionML.Model
{
    public class ModelInput
    {
        [ColumnName("vacid"), LoadColumn(0)]
        public float Vacid { get; set; }


        [ColumnName("Tocase"), LoadColumn(1)]
        public float Tocase { get; set; }


        [ColumnName("Stname"), LoadColumn(2)]
        public string Stname { get; set; }


        [ColumnName("Stcase"), LoadColumn(3)]
        public float Stcase { get; set; }


        [ColumnName("%case"), LoadColumn(4)]
        public float _case { get; set; }


        [ColumnName("Tovac"), LoadColumn(5)]
        public float Tovac { get; set; }


        [ColumnName("Stvac"), LoadColumn(6)]
        public float Stvac { get; set; }


    }
}
