// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace Covid_Vaccine_DistributionML.Model
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
