// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WebApplication1ML.Model
{
    public class ModelInput
    {
        [ColumnName("Feedbacktext"), LoadColumn(0)]
        public string Feedbacktext { get; set; }


        [ColumnName("value"), LoadColumn(1)]
        public string Value { get; set; }


    }
}
