// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SemanticML.Model
{
    public class ModelInput
    {
        [ColumnName("Feedbacktext"), LoadColumn(0)]
        public string Feedbacktext { get; set; }


        [ColumnName("value"), LoadColumn(1)]
        public bool Value { get; set; }


        [ColumnName("total feedback"), LoadColumn(2)]
        public float Total_feedback { get; set; }


        [ColumnName("no_acc_word"), LoadColumn(3)]
        public float No_acc_word { get; set; }


        [ColumnName("Percent"), LoadColumn(4)]
        public string Percent { get; set; }


    }
}
